#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_lunch:
    path: /api/lunch
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\RecipeController::list